export const MODELS = [
  { id: 1, text: "Mayumi Himura" },
  { id: 2, text: "Ai Musori" },
  { id: 3, text: "Sam Baas" },
  { id: 4, text: "Kyle Pred" },
  { id: 5, text: "Alan Crane" },
  { id: 6, text: "Emma Gaine" },
  { id: 7, text: "Mary Mushkin" },
  { id: 8, text: "Eddie Marshal" },
  { id: 9, text: "Dominic Toretti" },
  { id: 10, text: "Kitty Dream" },
  { id: 11, text: "example" },
  { id: 12, text: "example" },
  { id: 13, text: "example" },
  { id: 14, text: "example" },
  { id: 15, text: "example" },
];
