export const STAFF = [
  {
    id: 1,
    name: "Mayumi Himura",
    title: "Owner",
    isAdmin: true,
    isModel: true,
    importance: 0,
  },
  {
    id: 2,
    name: "Ai Musori",
    title: "Model",
    isAdmin: false,
    isModel: true,
    importance: 5,
  },
  {
    id: 3,
    name: "Sam Baas",
    title: "Model",
    isAdmin: false,
    isModel: true,
    importance: 5,
  },
  {
    id: 4,
    name: "Kyle Pred",
    title: "Model",
    isAdmin: false,
    isModel: true,
    importance: 5,
  },
  {
    id: 5,
    name: "Alan Crane",
    title: "Model",
    isAdmin: false,
    isModel: true,
    importance: 5,
  },
  {
    id: 6,
    name: "Emma Gaine",
    title: "Model",
    isAdmin: false,
    isModel: true,
    importance: 5,
  },
  {
    id: 7,
    name: "Mary Mushkin",
    title: "Model",
    isAdmin: false,
    isModel: true,
    importance: 5,
  },
  {
    id: 8,
    name: "Eddie Marshal",
    title: "Model",
    isAdmin: false,
    isModel: true,
    importance: 5,
  },
  {
    id: 9,
    name: "Dominic Toretti",
    title: "Model",
    isAdmin: false,
    isModel: true,
    importance: 5,
  },
  {
    id: 10,
    name: "Kitty Dream",
    title: "PR Specialist",
    isAdmin: false,
    isModel: true,
    importance: 3,
  },
  {
    id: 11,
    text: "example",
    title: "Model",
    isAdmin: false,
    isModel: true,
    importance: 5,
  },
  {
    id: 12,
    text: "example",
    title: "Model",
    isAdmin: false,
    isModel: true,
    importance: 5,
  },
  {
    id: 13,
    text: "example",
    title: "Model",
    isAdmin: false,
    isModel: true,
    importance: 5,
  },
  {
    id: 14,
    text: "example",
    title: "Model",
    isAdmin: false,
    isModel: true,
    importance: 5,
  },
  {
    id: 15,
    text: "example",
    title: "Model",
    isAdmin: false,
    isModel: true,
    importance: 5,
  },
  {
    id: 16,
    name: "Karina Dawn",
    title: "FTO",
    isAdmin: true,
    isModel: false,
    importance: 1,
  },
  {
    id: 17,
    name: "A Staff Member",
    title: "HR Manager",
    isAdmin: true,
    isModel: false,
    importance: 4,
  },
  {
    id: 18,
    name: "PERSON",
    title: "HR Manager",
    isAdmin: true,
    isModel: false,
    importance: 4,
  },
  {
    id: 19,
    name: "Jay Que",
    title: "Cleaner",
    isAdmin: false,
    isModel: false,
    importance: 3.9,
  },
  {
    id: 20,
    name: "Octavio Stenberg",
    title: "Head Photographer",
    isAdmin: false,
    isModel: false,
    importance: 3,
  },
  {
    id: 21,
    name: "A Staff Member",
    title: "Grunt",
    isAdmin: false,
    isModel: false,
    importance: 6,
  },
  {
    id: 22,
    name: "A Staff Member",
    title: "Grunt",
    isAdmin: false,
    isModel: false,
    importance: 6,
  },
  {
    id: 23,
    name: "A Staff Member",
    title: "Grunt",
    isAdmin: false,
    isModel: false,
    importance: 6,
  },
  {
    id: 24,
    name: "A Staff Member",
    title: "Grunt",
    isAdmin: false,
    isModel: false,
    importance: 6,
  },
  {
    id: 25,
    name: "A Staff Member",
    title: "Grunt",
    isAdmin: false,
    isModel: false,
    importance: 6,
  },
  {
    id: 26,
    name: "A Staff Member",
    title: "Grunt",
    isAdmin: false,
    isModel: false,
    importance: 6,
  },
  {
    id: 27,
    name: "A Staff Member",
    title: "Grunt",
    isAdmin: false,
    isModel: false,
    importance: 6,
  },
];
